config/routes.rb
Rails.application.routes.draw do
  root 'memes#index'
  devise_for :users, :controllers => {registrations: "registrations"}
  resources :memes
  post 'memes/new' => 'memes#get_images'
  get 'slack/sending' => 'slack#sending'

end

app/models/meme.rb
class Meme < ActiveRecord::Base

  belongs_to :user

	validates :raw_image_url, presence: true
	has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}


	def memeify(transformed_url)
		self.image = URI.parse(transformed_url)
		self.save
	end
end

app/models/search.rb
class Search
  def self.current=(images)
    @current = images
  end
  def self.current
    current = @current
    @current = nil
    return current
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memes, dependent: :destroy

  validates :username, presence: true, length: { minimum: 4, maximum: 16 }

  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memes_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'search.rb'

class MemesController < ApplicationController

	include MemesHelper

	before_action :authenticate_user!, except: [:index]
	before_action :set_meme, only: [:edit, :update, :destroy]
	before_action :owned_meme, only: :destroy

	def index
		@memes = Meme.all.order('created_at DESC').page(params[:page])
	end

	def get_images
		search = url_convert(params[:search])
		response = getty_request(search)
		Search.current=(response)
		redirect_to request.referer
	end

	def new
		@images = Search.current
	end

	def create
		@meme = current_user.memes.build(raw_image_url: image_params[:image_ref])
		if @meme.save
			flash[:notice]='Image added to meme'
			redirect_to edit_meme_path(@meme.id)
		else
			flash[:alert]= "Uh oh! Couldn't create your meme!"
			redirect_to request.referer
		end
	end

	def edit
		@meme
	end

	def update
		transform_info = transform_image(@meme, meme_params)
		transformed_url = upload_image(transform_info)["url"]
		@meme.memeify(transformed_url)
		flash[:notice]= "Woohoo! Meme added"
		redirect_to memes_path
	end

	def destroy
		if @meme.destroy
      flash[:notice] = "Your meme was successfully deleted!"
      redirect_to memes_path
    else
      flash[:alert] = "Uh oh! Couldn't delete your meme!"
      redirect_to memes_path
    end
	end

	private
	def meme_params
		params.require(:meme).permit(:top_caption, :bottom_caption)
	end

	def image_params
		params.permit(:image_ref)
	end

	def owned_meme
    unless @meme.user == current_user
      flash[:alert] = "That meme doesn't belong to you!"
      redirect_to root_path
    end
  end

	def set_meme
    @meme = Meme.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

def sign_up_params
  params.require(:user).permit(:email, :username, :password, :password_confirmation)
end

end

app/controllers/slack_controller.rb
class SlackController < ApplicationController

  def sending
    if params[:codeword].downcase == ENV['CODE_WORD']
      flash[:notice]='Correct codeword'
      url = URI.parse("https://hooks.slack.com")
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(ENV['SLACK_HOOK'], {'Content-Type' =>'application/json'})
      request.body = {"username" => "Memeories", "icon_url" => "http://res.cloudinary.com/dv9revqig/image/upload/v1465558784/logo_graphicv2_srrvsc.jpg", "text" => params[:text]}.to_json
      response = http.request(request)
      redirect_to '/'
    else
      flash[:alert]='Incorrect codeword'
      redirect_to '/'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memes_helper.rb
require 'erb'

module MemesHelper

	def url_convert(string)
		encoded_string = ERB::Util.url_encode(string)
		encoded_string.gsub('%2C','%252C')
	end

	def getty_request(search)
		url = URI.parse("https://api.gettyimages.com")
		search_url = "/v3/search/images?fields=id,title,comp,referral_destinations&sort_order=best&phrase=#{search}"
		req = Net::HTTP::Get.new(search_url)
		http = Net::HTTP.new(url.host, url.port)
		http.use_ssl = true
		req['Api-Key']=ENV['GETTY_ACCESS_KEY']
		response = http.start do |http|
  		http.request(req)
		end
		translate_response(response)
	end

	def translate_response(response)
		response = JSON.parse(response.body)
		response = response["images"].map{ |image| image["display_sizes"][0]["uri"]}
	end

	def upload_image(raw_image_url)
		Cloudinary::Uploader.upload(raw_image_url)
	end

	def transform_image(meme, meme_params)
		public_id = upload_image(meme.raw_image_url)["public_id"]
		url_top = url_convert(meme_params[:top_caption])
		url_bottom = url_convert(meme_params[:bottom_caption])
		Cloudinary::Utils.cloudinary_url(public_id, transform_settings(url_top,url_bottom))
	end

	def transform_settings(url_top,url_bottom)
		{:transformation => [
				{:overlay => "text:helvetica_35_bold_line_spacing_0_center_stroke:#{url_top}", :color => "white", :border=>"5px_solid_black",
				:gravity => :north, :crop => "fit", :width => 320 },
				{:overlay => "text:helvetica_35_bold_line_spacing_0_center_stroke:#{url_bottom}", :color => "white", :border=>"5px_solid_black",
				:gravity => :south, :crop => "fit", :width => 320 }]}
	end

end

app/helpers/slack_helper.rb
module SlackHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memeories</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to image_tag("/logo_30.jpg"), memes_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Make meme", new_meme_path %></li>
      <% if current_user %>
        <li><%= link_to current_user.username, "#" %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

app/views/memes/edit.erb
<div style="text-align:center" class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for @meme do |f| %>
      <%= f.label :top_caption %>
      <%= f.text_field :top_caption, :size => 48 %>
      <br>
      <%= image_tag @meme.raw_image_url %>
      <br>
      <%= f.label :bottom_caption %>
      <%= f.text_field :bottom_caption, :size => 45 %>
      <br><br>
      <%= f.submit "Create" %>
    <% end %>
    <br><br>
    <%= link_to "Cancel", meme_path(@meme.id), method: :delete %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/memes/index.erb
<div class="background">
  <div class="content">
<% @memes.each do |meme| %>
  <div style="text-align:center" class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= image_tag(meme.image.url) %>

      <div style="text-align:center;" class="row">
        <div class="col-md-4"></div>
          <div style="text-color:#000000; background-color:#fff" class="col-md-4">
        <h4>by <br><%= meme.user.username %></h4>
        <% if current_user == meme.user %>
          <a style="background-color:#fff"><%= link_to "Delete", meme_path(meme.id), method: :delete %></a>
        <% end %>
        </div>
          <div class="col-md-4"></div>
      </div>
      <br>
      <% if current_user %>
        <form action="/slack/sending" method=GET>
          <input type="hidden" name='text' value= "<%='Sent by ' + current_user.username%> <%= meme.image.url%>">
          <input type="text" name='codeword' placeholder="Code Word">
          <br>
          <input type="submit" value="Share on Slack">
        </form>
        <br>
      <% end %>
  </div>
  <div class="col-md-3"></div>
  </div>
  <br><br>
<% end %>

<div style="text-align:center; background-color:#ffffff">
  <%= paginate @memes %>
</div>
</div>
</div>

app/views/memes/new.erb
<div style="text-align:center">
  <%= form_tag("/memes/new", method: "post") do %>
    <%= label_tag(:search, "Search for image:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>
<% if @images %>
  <% @images.each_with_index do |image,index| %>
    <div style="text-align:center" class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <%= link_to image_tag(image), memes_path(image_ref: image), method: :post, id: (index).to_s %>
      </div>
      <div class="col-md-3"></div>
    </div>
    <br><br>
  <% end %>
<% end %>